name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: ðŸŽ‰ iOS Build
    runs-on: macos-latest
    defaults:
      run:
        working-directory: frontend/mobile
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: 'stable'
          architecture: x64

      - run: flutter pub get

      - run: pod repo update
        working-directory: frontend/mobile/ios

      - run: flutter build ios --release --no-codesign

      - run: mkdir Payload
        working-directory: frontend/mobile/build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: frontend/mobile/build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: frontend/mobile/build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: frontend/mobile/build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
